---
title: "CodeBook.Rmd"
author: "Stephen D. Beckwith (embeddedsteve@gmail.com)"
date: "October 25, 2014"
output: html_document
---

## Getting and Cleaning Data  
#### Coursera class (# 3 in the Data Scientist Series)

### Course Acknowledgement:
Grateful Acknowledgment of the DataSet Used:   
[1] Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and 
Jorge L. Reyes-Ortiz. Human Activity Recognition on Smartphones using a 
Multiclass Hardware-Friendly Support Vector Machine. International Workshop of
Ambient Assisted Living (IWAAL 2012). Vitoria-Gasteiz, Spain. Dec 2012.
This dataset is distributed AS-IS and no responsibility implied or explicit can
be addressed to the authors or their institutions for its use or misuse. Any
commercial use is prohibited. Jorge L. Reyes-Ortiz, Alessandro Ghio,
Luca Oneto, Davide Anguita. November 2012.

### Course Objective:
The purpose of this project is to demonstrate your ability to collect, work with, and clean a data set. The goal is to prepare tidy data that can be used for later analysis. You will be graded by your peers on a series of yes/no questions related to the project. You will be required to submit: 1) a tidy data set as described below, 2) a link to a Github repository with your script for performing the analysis, and 3) a code book that describes the variables, the data, and any transformations or work that you performed to clean up the data called CodeBook.md. You should also include a README.md in the repo with your scripts. This repo explains how all of the scripts work and how they are connected.  

One of the most exciting areas in all of data science right now is wearable computing - see for example this article . Companies like Fitbit, Nike, and Jawbone Up are racing to develop the most advanced algorithms to attract new users. The data linked to from the course website represent data collected from the accelerometers from the Samsung Galaxy S smartphone. A full description is available at the site where the data was obtained: 

http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones 

Here are the data for the project: 

https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip 

You should create one R script called run_analysis.R that does the following. 
   1) Merges the training and the test sets to create one data set.
   2) Extracts only the measurements on the mean and standard deviation for each measurement. 
   3) Uses descriptive activity names to name the activities in the data set
   4) Appropriately labels the data set with descriptive variable names. 
   5) From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.

### Data Set Details
  When the dataset is extracted, it ends up on a folder/directory called:  **UCI HCR Dataset**
  In this folder/directory is a **README.txt** that provides the details on the various contents of this dataset and provides guidance as to the various component parts and the information they convey.
  

### Overall Project Requirements:
 - Combine the Test subject data (3 files worth) with the Train subject data (3 files worth) into a single file
 - Strip this data of components NOT containing the words *mean* or *std* in their name
 - Tidy this up and take the mean (average) of each variable in the dataset.

### Final Variable List
   The following table lists the *mean* and *std* features from the overall feature set we have accumulated in our dataset, including the suject and activity columns.  There are a total of 30 subjects, each with 6 different activites, resulting in a table that is 180 x 68 in the final tidy dataset.
   
| Variable | Descritpion
| -------- |---------
| Activity | The activity peformed.
| Subject | The ID of the subject.
| tBodyAcc-mean()-X | Mean time for acceleration of body for X direction.
| tBodyAcc-mean()-Y | Mean time for acceleration of body for Y direction.
| tBodyAcc-mean()-Z | Mean time for acceleration of body for Z direction.
| tBodyAcc-std()-X | Standard deviation of time for acceleration of body for X direction.
| tBodyAcc-std()-Y | Standard deviation of time for acceleration of body for Y direction.
| tBodyAcc-std()-Z | Standard deviation of time for acceleration of body for Z direction.
| tGravityAcc-mean()-X | Mean time of acceleration of gravity for X direction.
| tGravityAcc-mean()-Y | Mean time of acceleration of gravity for Y direction.
| tGravityAcc-mean()-Z | Mean time of acceleration of gravity for Z direction.
| tGravityAcc-std()-X | Standard deviation of time of acceleration of gravity for X direction.
| tGravityAcc-std()-Y | Standard deviation of time of acceleration of gravity for Y direction.
| tGravityAcc-std()-Z | Standard deviation of time of acceleration of gravity for Z direction.
| tBodyAccJerk-mean()-X | Mean time of body acceleration jerk for X direction.
| tBodyAccJerk-mean()-Y | Mean time of body acceleration jerk for Y direction
| tBodyAccJerk-mean()-Z | Mean time of body acceleration jerk for Z direction
| tBodyAccJerk-std()-X | Standard deviation of time of body acceleration jerk for X direction.
| tBodyAccJerk-std()-Y | Standard deviation of time of body acceleration jerk for Y direction.
| tBodyAccJerk-std()-Z | Standard deviation of time of body acceleration jerk for Z direction.
| tBodyGyro-mean()-X | Mean body gyroscope measurement for X direction.
| tBodyGyro-mean()-Y | Mean body gyroscope measurement for Y direction.
| tBodyGyro-mean()-Z | Mean body gyroscope measurement for Z direction.
| tBodyGyro-std()-X | Standard deviation of body gyroscope measurement for X direction.
| tBodyGyro-std()-Y | Standard deviation of body gyroscope measurement for Y direction.
| tBodyGyro-std()-Z | Standard deviation of body gyroscope measurement for Z direction.
| tBodyGyroJerk-mean()-X | Mean jerk signal of body for X direction.
| tBodyGyroJerk-mean()-Y | Mean jerk signal of body for Y direction.
| tBodyGyroJerk-mean()-Z | Mean jerk signal of body for Z direction.
| tBodyGyroJerk-std()-X | Standard deviation of jerk signal of body for X direction.
| tBodyGyroJerk-std()-Y | Standard deviation of jerk signal of body for Y direction.
| tBodyGyroJerk-std()-Z | Standard deviation of jerk signal of body for Z direction.
| tBodyAccMag-mean() | Mean magnitude of body Acc
| tBodyAccMag-std() | Standard deviation of magnitude of body Acc
| tGravityAccMag-mean() | Mean gravity acceleration magnitude.
| tGravityAccMag-std() | Standard deviation of gravity acceleration magnitude.
| tBodyAccJerkMag-mean() | Mean magnitude of body acceleration jerk.
| tBodyAccJerkMag-std() | Standard deviation of magnitude of body acceleration jerk.
| tBodyGyroMag-mean() | Mean magnitude of body gyroscope measurement.
| tBodyGyroMag-std() | Standard deviation of magnitude of body gyroscope measurement.
| tBodyGyroJerkMag-mean() | Mean magnitude of body body gyroscope jerk measurement.
| tBodyGyroJerkMag-std() | Standard deviation of magnitude of body body gyroscope jerk measurement.
| fBodyAcc-mean()-X | Mean frequency of body acceleration for X direction.
| fBodyAcc-mean()-Y | Mean frequency of body acceleration for Y direction.
| fBodyAcc-mean()-Z | Mean frequency of body acceleration for Z direction.
| fBodyAcc-std()-X | Standard deviation of frequency of body acceleration for X direction.
| fBodyAcc-std()-Y | Standard deviation of frequency of body acceleration for Y direction.
| fBodyAcc-std()-Z | Standard deviation of frequency of body acceleration for Z direction.
| fBodyAccJerk-mean()-X | Mean frequency of body accerlation jerk for X direction.
| fBodyAccJerk-mean()-Y | Mean frequency of body accerlation jerk for Y direction.
| fBodyAccJerk-mean()-Z | Mean frequency of body accerlation jerk for Z direction.
| fBodyAccJerk-std()-X | Standard deviation frequency of body accerlation jerk for X direction.
| fBodyAccJerk-std()-Y | Standard deviation frequency of body accerlation jerk for Y direction.
| fBodyAccJerk-std()-Z | Standard deviation frequency of body accerlation jerk for Z direction.
| fBodyGyro-mean()-X | Mean frequency of body gyroscope measurement for X direction.
| fBodyGyro-mean()-Y | Mean frequency of body gyroscope measurement for Y direction.
| fBodyGyro-mean()-Z | Mean frequency of body gyroscope measurement for Z direction.
| fBodyGyro-std()-X | Standard deviation frequency of body gyroscope measurement for X direction.
| fBodyGyro-std()-Y | Standard deviation frequency of body gyroscope measurement for Y direction.
| fBodyGyro-std()-Z | Standard deviation frequency of body gyroscope measurement for Z direction.
| fBodyAccMag-mean() | Mean frequency of body acceleration magnitude.
| fBodyAccMag-std() | Standard deviation of frequency of body acceleration magnitude.
| fBodyBodyAccJerkMag-mean() | Mean frequency of body acceleration jerk magnitude.
| fBodyBodyAccJerkMag-std() | Standard deviation of frequency of body acceleration jerk magnitude.
| fBodyBodyGyroMag-mean() | Mean frequency of magnitude of body gyroscope measurement.
| fBodyBodyGyroMag-std() | Standard deviation of frequency of magnitude of body gyroscope measurement.
| fBodyBodyGyroJerkMag-mean() | Mean frequency of magnitude of body gyroscope jerk measurement.


